version: '3'

services:
  frontend:
    build:
      context: ./cocktails-web
      dockerfile: Dockerfile.dev
    container_name: cocktails-web-dev
    ports:
      - "3000:3000"
    volumes:
      - ./cocktails-web:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - web.env
    depends_on:
      - api
      - ldap

  api:
    build: ./cocktails-api
    container_name: cocktails-api-dev
    ports:
      - "5000:5000"
    volumes:
      - ./cocktails-api:/app
    depends_on:
      - ldap
      - db
    command: flask run --host 0.0.0.0 --port 5000 --reload
    env_file:
      - api.env
    restart: unless-stopped

  db:
    image: postgres:latest
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 1s

  ldap:
    image: osixia/openldap:latest
    container_name: ldap
    env_file:
      ldap.env
    tty: true
    stdin_open: true
    volumes:
      - ldap_data:/var/lib/ldap
    ports:
      - "389:389"
      - "636:636"
    domainname: "parcerisa.xyz" # important: same as hostname
    hostname: "parcerisa.xyz"

  ldapadmin:
    image: osixia/phpldapadmin:latest
    ports:
      - '8080:80'
    env_file:
      - ldapadmin.env
    depends_on:
      - ldap

volumes:
  db_data:
  ldap_data: