version: '3'

services:
  frontend:
    build:
      context: ./cocktails-web
      dockerfile: Dockerfile.dev
    container_name: cocktails-web-dev
    ports:
      - "3000:3000"
    volumes:
      - ./cocktails-web:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000

  api:
    build: ./cocktails-api
    container_name: cocktails-api-dev
    ports:
      - "5000:5000"
    volumes:
      - ./cocktails-api:/app
    depends_on:
      - users
      - db
    command: flask run --host 0.0.0.0 --port 5000 --reload
    environment:
      - DATABASE_URL=postgresql://cocktails:lojfR21hDCzU6uCtg6q4@db:5432/cocktails
      - USERS_DATABASE_URL=postgresql://cocktails:lojfR21hDCzU6uCtg6q4@db:5431/users
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: cocktails
      POSTGRES_PASSWORD: lojfR21hDCzU6uCtg6q4
      POSTGRES_DB: cocktails
    ports:
      - "5432:5432"

  users:
    image: postgres:latest
    environment:
      POSTGRES_USER: cocktails
      POSTGRES_PASSWORD: lojfR21hDCzU6uCtg6q4
      POSTGRES_DB: users
    ports:
      - "5431:5432"